# 에러처리

## async/await 에러
- await문에서 에러가 나면 javascript는 더 이상 코드를 실행시키지 않는다.
- try / catch문을 사용하고, 에러가 발생하면 실행될 catch문에 페이지를 다시 랜더하고 페이지에 보여줄 에러 메시지를 넘겨준다.
```js

  // controller.js
  
  export const postUpload = async(req, res) => {
    const { title, description, hashtags } = req.body

    try {
      throw error
      return res.redirect('/');
    } catch(error) {
      console.log(error)
      // 에러가 발생하면 다시 업로드하는 페이지를 랜더한다.
      return res.render('upload', { pageTitle: 'Upload Video', errorMessage: error._message });
    }
  }

```
- template에서 조건문을 사용해 에러메세지 작성
```pug

  //- upload.pug

  extends base.pug

  block content
    if errorMessage
      span=errorMessage
    form
      input...
      input...

```
